## Data Preprocessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('shuffled_final_result1.csv')

In [3]:
dataset.head(n=10)

word   language
0      maken      Dutch
1    संभावित      Hindi
2       ooit      Dutch
3         항해     Korean
4      també    Catalan
5      reply   Javanese
6     rehefa   Malagasy
7     kamusi    Swahili
8     heller     Danish
9  хөгжилтэй  Mongolian

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)

In [5]:
x = dataset.iloc[:, 0].values

In [6]:
x

array(['maken', 'संभावित', 'ooit', ..., 'ეზოში', 'entzun', 'ery'],
      dtype=object)

In [7]:
x.size

103001

In [8]:
y = dataset.iloc[:, 1].values

In [9]:
y

array(['Dutch', 'Hindi', 'Dutch', ..., 'Georgian', 'Basque', 'Malagasy'],
      dtype=object)

In [10]:
x_ = cv.fit_transform(x.astype('U')).toarray()

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_, y, test_size = 0.2, random_state = 0)

In [12]:
len(x_)

103001

In [13]:
len(y)

103001

In [14]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_, y)

GaussianNB()

In [15]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
x_

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [17]:
len(x_train[0])

1500

In [18]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Japanese' 'Turkish']
 ['Japanese' 'Polish']
 ['Japanese' 'Greek']
 ...
 ['Japanese' 'Czech']
 ['Bengali' 'Bengali']
 ['Japanese' 'Serbian']]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0 ...  0  0  1]
 [ 0  9  0 ...  0  0  2]
 [ 0  0  2 ...  0  0  0]
 ...
 [ 0  0  0 ... 71  0  0]
 [ 0  0  0 ...  0 16  0]
 [ 0  0  0 ...  0  0  3]]


0.0691713994466288

In [20]:
single_review = ['stars are beautiful']

In [21]:
single_ = cv.transform(single_review).toarray()

In [22]:
single_

array([[0, 0, 0, ..., 0, 0, 0]])

In [23]:
classifier.predict(single_)

array(['Japanese'], dtype='<U13')

In [24]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_, y)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)